config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  # omniauth 認證
  # get'/auth/facebook/callback' , to: "user/omniauth_callbacks#callback"
  # get'/auth/google_oauth2/callback' , to: "user/omniauth_callbacks#callback"
  # get'/auth/line/callback' , to: "user/omniauth_callbacks#callback"

  # get '/auth/failure', to: "user/omniauth_callbacks#failure"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :home

  namespace :admin do
    resource :session, controller: "session"
  end
  resource :admin, controller: "admin"

  namespace :backends do
    resource :system, controller: "system"

    resources :images do
      collection do
        post :sort
        post :ck_upload
      end
    end

    # resources dry controllers
    resources :resources do
      collection do
        post :sort
      end
      member do
        post :event
      end
    end

  end
  resources :backends

  # 語言包管理
  resources :iye

end

app/views/admin/_form.html.erb
<div class="form-group">
  <label class="col-lg-3 col-sm-3 control-label"><%= Admin.human_attribute_name('name') %></label>
  <div class="col-lg-9">
    <input type="text" class="form-control" name="admin[name]" value="<%= current_object.name %>" />
  </div>
</div>
<div class="form-group">
  <label class="col-lg-3 col-sm-3 control-label"><%= Admin.human_attribute_name('email') %></label>
  <div class="col-lg-9">
    <input type="text" class="form-control" name="admin[email]" value="<%= current_object.email %>" />
  </div>
</div>
<div class="form-group">
  <label class="col-lg-3 col-sm-3 control-label"><%= Admin.human_attribute_name('password') %></label>
  <div class="col-lg-9">
    <input type="password" class="form-control" name="admin[password]" />
  </div>
</div>
<div class="form-group">
  <label class="col-lg-3 col-sm-3 control-label"><%= Admin.human_attribute_name('password_confirmation') %></label>
  <div class="col-lg-9">
    <input type="password" class="form-control" name="admin[password_confirmation]" />
  </div>
</div>
<div class="form-group">
<label class="col-lg-3 col-sm-3 control-label"></label>
  <div class="col-lg-9">
    <button class="btn btn-danger">
      <%= t 'backends.submit' %>
    </button>
  </div>
</div>

app/views/admin/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <nav class="navbar navbar-inverse" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="fa fa-bars"></span>
        </button>
        <a class="navbar-brand" href="#"><%= t('backends.nav')%></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">

        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <section class="panel">
      <header class="panel-heading">
        <%= Admin.model_name.human %>
      </header>
      <div class="panel-body">
        <form action="<%= admin_path %>" method="post" class="form-horizontal" > 
          <%= token_tag nil %>
          <input type="hidden" name="_method" value="put" >
          <%= render partial: "/admin/form",locals: {current_object: current_object} %>
        </form>
      </div>
    </section>
  </div>
</div>      