config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  # omniauth 認證
  # get'/auth/facebook/callback' , to: "user/omniauth_callbacks#callback"
  # get'/auth/google_oauth2/callback' , to: "user/omniauth_callbacks#callback"
  # get'/auth/line/callback' , to: "user/omniauth_callbacks#callback"

  # get '/auth/failure', to: "user/omniauth_callbacks#failure"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :home

  namespace :admin do
    resource :session, controller: "session"
  end
  resource :admin, controller: "admin"

  namespace :backends do
    resource :system, controller: "system"

    resources :images do
      collection do
        post :sort
        post :ck_upload
      end
    end

    # resources dry controllers
    resources :resources do
      collection do
        post :sort
      end
      member do
        post :event
      end
    end

  end
  resources :backends

  # 語言包管理
  resources :iye

end

app/controllers/backends/images_controller.rb
class Backends::ImagesController < BackendsController

  skip_before_action :verify_authenticity_token

  def ck_upload
    @image = Image.create(file: params[:upload])

    respond_to do |format|
      format.js {

      }
      format.html {
        render layout: false, plain: %Q(<html><body><script type="text/javascript">window.parent.CKEDITOR.tools.callFunction('#{params[:CKEditorFuncNum]}', "#{@image.file.url}\");</script></body></html>)
      }
    end  

  end

app/controllers/backends/resources_controller.rb
class Backends::ResourcesController < BackendsController
  before_action :breadcrumb

  include RestfulResource

  def breadcrumb
    begin 
    add_breadcrumb model_class.model_name.human, url_for(action: :index)
    rescue
      
    end
    
    begin 
      add_breadcrumb current_object.name, url_for(action: :show)
    rescue

    end
  end

end

app/controllers/backends/system_controller.rb
class Backends::SystemController < Backends::ResourcesController

  def edit

  end

  private

  def current_object
    # 用 default_scope 限制搜尋的範圍
    @current_object ||= current_system
  end

  def permitted_attributes
    [
      :name, 
      :title, 
      :description, 
      :keyword, 
      :phone,
      :address, 
      :email,
    ] + System.stored_attributes[:socials].map(&:to_sym)
  end  


end

app/controllers/backends_controller.rb
class BackendsController < ApplicationController

  before_action :login?

  def index

  end

  private

  def login?
    unless current_admin
      respond_to do |format|
        format.html {
          session[:origin_url] = request.original_url 
          redirect_to new_admin_session_path
        }
      end 
    end
  end

end

app/helpers/backends/resources_helper.rb
module Backends::ResourcesHelper
end

app/helpers/backends/system_helper.rb
module Backends::SystemHelper
end

app/helpers/backends_helper.rb
module BackendsHelper
end

app/views/backends/partials/_footer.html.erb
<footer class="site-footer">
  <div class="text-center">
    2016 &copy; PlayPlus
    <a href="#" class="go-top"> <i class="fa fa-angle-up"></i> </a>
  </div>
</footer>

app/views/backends/partials/_header.html.erb
<header class="header white-bg">
  <div class="sidebar-toggle-box">
    <div data-original-title="Toggle Navigation" data-placement="right" class="fa fa-bars tooltips"></div>
  </div>
  <!--logo start-->
  <a href="<%= backends_path %>" class="logo" ><%= current_system.name %><span></span></a>
  <!--logo end-->
  <div class="nav notify-row" id="top_menu">
    <!--  notification start -->

  </div>
  <div class="top-nav ">
    <ul class="nav pull-right top-menu">
      <!-- <li>
      <input type="text" class="form-control search" placeholder="Search">
      </li> -->
      <!-- user login dropdown start-->
      <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
          <img alt="" src="http://www.placehold.it/29x29/EFEFEF/AAAAAA">
          <span class="username"><%= current_admin.name %></span> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu extended logout">
          <div class="log-arrow-up"></div>
          <!-- <li>
          <a href="/backend/edit"><i class=" fa fa-suitcase"></i><%= yield(:profile) %></a>
          </li>
          <li>
          <a href="/backend/system"><i class="fa fa-cog"></i><%= yield(:settings) %></a>
          </li>
          <li>
          <a href="/backend/index"><i class="fa fa-bell-o"></i><%= yield(:notification) %></a>
          </li> -->
          <li>
            <%= link_to '登出' , admin_session_path , method: :delete %>
          </li>
        </ul>
      </li>

      <!-- user login dropdown end -->
      <!-- <li class="sb-toggle-right">
      <i class="fa  fa-align-right"></i>
      </li> -->
    </ul>
  </div>
</header>

app/views/backends/partials/_modal.html.erb
<div class="modal fade " id="MyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
          ×
        </button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button data-dismiss="modal" class="btn btn-default" type="button">
          關閉
        </button>
      </div>
    </div>
  </div>
</div>
<script>
  //呼叫 Modal
  $(document).on('click',"[data-target='#MyModal']",function(e){
    e.preventDefault();
    var title = $(this).data('title');
    var action = $(this).data('action');
    var current_action = $("#MyModal").data('action');
    if (current_action == action) {
      $("#MyModal").modal('show')
      return
    }
    $("#MyModal").data('action', action)
    $("#MyModal .modal-title").text(title);
    $("#MyModal .modal-body").load(action);
    $("#MyModal").modal('show')   
  })
</script>

app/views/backends/partials/_sidebar.html.erb
<aside>
  <div id="sidebar"  class="nav-collapse ">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu" id="nav-accordion">
      <li>
        <a href="<%= backends_path %>"> <i class="fa fa-dashboard"></i> <span>首頁</span> </a>
      </li>

      <!-- 展開式 menu -->
      <!-- <li class="sub-menu dcjq-parent-li">
        <a href="javascript:;" class="dcjq-parent <%= active(controller_name, "") %>">
          <i class="fa fa-tasks"></i>
          <span>Item</span>
          <span class="dcjq-icon"></span>
        </a>
        <ul class="sub">
          <li class="<%= active(controller_name, "") %>">
            <a href="#">
              <i class="fa fa-star"></i> <span>items</span>
            </a>
          </li>
        </ul>
      </li>  --> 

      <li>
        <a class="<%= active(controller_name, "admin") %>" href="<%= edit_admin_path %>">
          <i class="fa fa-star"></i> <span><%= Admin.model_name.human %></span>
        </a>
      </li>
      <li >
        <a class="<%= active(controller_name, "system") %>" href="<%= edit_backends_system_path %>" >
          <i class="fa fa-star"></i> <span><%= System.model_name.human %></span>
        </a>
      </li>
    </ul>
    <!-- sidebar menu end-->
  </div>
</aside>

app/views/backends/partials/_toastr.html.erb
<div id="toastr" data-success="<%= flash[:success] %>" data-error="<%= flash[:error] %>"></div>
<script>
  $(document).ready(function() {
    var success = $("#toastr").data('success')
    var error = $("#toastr").data('error')
    toastr.options = {
      closeButton : true,
      debug : false,
      progressBar : false,
      positionClass : "toast-top-right",
      onclick : null,
      showDuration : "300",
      hideDuration : "1000",
      timeOut : "4000",
      extendedTimeOut : "1000",
      showEasing : "swing",
      hideEasing : "linear",
      showMethod : "fadeIn",
      hideMethod : "fadeOut"
    };
    if (success != "") {
      toastr.success(success);
    }
    if (error != "") {
      toastr.error(error);
    }
  }); 
</script>