config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  # omniauth 認證
  # get'/auth/facebook/callback' , to: "user/omniauth_callbacks#callback"
  # get'/auth/google_oauth2/callback' , to: "user/omniauth_callbacks#callback"
  # get'/auth/line/callback' , to: "user/omniauth_callbacks#callback"

  # get '/auth/failure', to: "user/omniauth_callbacks#failure"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :home

  namespace :admin do
    resource :session, controller: "session"
  end
  resource :admin, controller: "admin"

  namespace :backends do
    resource :system, controller: "system"

    resources :images do
      collection do
        post :sort
        post :ck_upload
      end
    end

    # resources dry controllers
    resources :resources do
      collection do
        post :sort
      end
      member do
        post :event
      end
    end

  end
  resources :backends

  # 語言包管理
  resources :iye

end

app/models/system.rb
# == Schema Information
#
# Table name: systems
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  keywords    :string
#  name        :string
#  email       :string
#  phone       :string
#  address     :string
#  socials     :text
#  deleted_at  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class System < ApplicationRecord

  store :socials, accessors: [ :facebook ]

end

app/controllers/backends/images_controller.rb
class Backends::ImagesController < BackendsController

  skip_before_action :verify_authenticity_token

  def ck_upload
    @image = Image.create(file: params[:upload])

    respond_to do |format|
      format.js {

      }
      format.html {
        render layout: false, plain: %Q(<html><body><script type="text/javascript">window.parent.CKEDITOR.tools.callFunction('#{params[:CKEditorFuncNum]}', "#{@image.file.url}\");</script></body></html>)
      }
    end  

  end

app/controllers/backends/resources_controller.rb
class Backends::ResourcesController < BackendsController
  before_action :breadcrumb

  include RestfulResource

  def breadcrumb
    begin 
    add_breadcrumb model_class.model_name.human, url_for(action: :index)
    rescue
      
    end
    
    begin 
      add_breadcrumb current_object.name, url_for(action: :show)
    rescue

    end
  end

end

app/controllers/backends/system_controller.rb
class Backends::SystemController < Backends::ResourcesController

  def edit

  end

  private

  def current_object
    # 用 default_scope 限制搜尋的範圍
    @current_object ||= current_system
  end

  def permitted_attributes
    [
      :name, 
      :title, 
      :description, 
      :keyword, 
      :phone,
      :address, 
      :email,
    ] + System.stored_attributes[:socials].map(&:to_sym)
  end  


end

app/controllers/backends_controller.rb
class BackendsController < ApplicationController

  before_action :login?

  def index

  end

  private

  def login?
    unless current_admin
      respond_to do |format|
        format.html {
          session[:origin_url] = request.original_url 
          redirect_to new_admin_session_path
        }
      end 
    end
  end

end

app/helpers/backends/resources_helper.rb
module Backends::ResourcesHelper
end

app/helpers/backends/system_helper.rb
module Backends::SystemHelper
end

app/helpers/backends_helper.rb
module BackendsHelper
end

app/views/backends/system/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <nav class="navbar navbar-inverse" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="fa fa-bars"></span>
        </button>
        <a class="navbar-brand" href="#"><%= t('backends.nav') %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        系統設定
      </header>
      <div class="panel-body">
        <%= form_tag(backends_system_path, multipart: true, method: :put, class: "form-horizontal") do %>
        <div class="row">
          <div class="col-md-2">
            <label class="control-label">網站設定</label>
          </div>
          <div class="col-md-10">

            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('title') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[title]" value="<%= current_object.title %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('description') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[description]" value="<%= current_object.description %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('keywords') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[keywords]" value="<%= current_object.keywords %>">
              </div>
            </div>                    
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <label class="control-label">基本資料</label>
          </div>
          <div class="col-md-10">
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('name') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[name]" value="<%= current_object.name %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('phone') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[phone]" value="<%= current_object.phone %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('email') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[email]" value="<%= current_object.email %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name('address') %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[address]" value="<%= current_object.address %>">
              </div>
            </div>            
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <label class="control-label">社群連結</label>
          </div>
          <div class="col-md-10">
            <% System.stored_attributes[:socials].each do |social| %>
            <div class="form-group">
              <label class="col-lg-3 col-sm-3 control-label"><%= System.human_attribute_name(social) %></label>
              <div class="col-lg-9">
                <input type="text" class="form-control" name="system[<%= social %>]" value="<%= current_object.send(social) %>">
              </div>
            </div>   
            <% end %>         
          </div>
        </div>            
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <button type="submit" data-disable-with="<%= t("backends.submiting") %>" class="btn btn-danger">
              <%= t("backends.submit") %>
            </button>
          </div>
        </div>
        <% end %>
      </div>
    </section>
  </div>
</div>